name: Continuous Integration
# trigger on push to repo
on: [push]

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install CMake
        run: sudo apt install cmake
      - name: Create build directory
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build
      - name: CMake configure
        run: cd $GITHUB_WORKSPACE/build && cmake ..
      - name: Build
        run: cd $GITHUB_WORKSPACE/build && make -j`nproc`
